SenseedDataCenter/Models/AnemometerRecord.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace SenseedDataCenter.Models
{
    public class AnemometerRecord
    {
        public int Id { get; set; }

        [Display(Name = "东西向风速")]
        public float E2W { get; set; }

        [Display(Name = "南北向风速")]
        public float N2S { get; set; }

        [Display(Name = "风速")]
        public float Velocity { get; set; }

        [Display(Name = "风向")]
        public float Direction { get; set; }

        [Display(Name = "声速")]
        public float SoundVelocity { get; set; }

        public string ProductId { get; set; }

        [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        [Display(Name = "检测时刻")]
        [DataType(DataType.DateTime)]
        public DateTime RecordDate { get; set; }
    }
}

SenseedDataCenter/Controllers/AnemometerRecordsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SenseedDataCenter.Models;

namespace SenseedDataCenter.Controllers
{
    public class AnemometerRecordsController : Controller
    {
        private readonly SenseedDataCenterContext _context;

        public AnemometerRecordsController(SenseedDataCenterContext context)
        {
            _context = context;
        }

        // GET: AnemometerRecords
        [Authorize]
        public async Task<IActionResult> Index(DateTime? startTime, DateTime? stopTime, string id, int pageIndex = 1)
        {
            int pageSize = 20;

            //var records = from record in _context.AnemometerRecords
            //    where record.ProductId == id
            //    select record;

            var records = _context.AnemometerRecords.OrderByDescending(record => record.RecordDate).Where(record => record.ProductId == id);

            if (startTime != null)
            {
                records = records.Where(s => s.RecordDate >= startTime);
            }

            if (stopTime != null)
            {
                records = records.Where(s => s.RecordDate <= stopTime);
            }

            var temp = records.Count();

            if (temp > 100)
            {
                temp = 100;
            }

            var pageCount = temp % pageSize == 0
                ? temp / pageSize
                : temp / pageSize + 1;

            var resultRecords = records.Skip((pageIndex - 1) * pageSize).Take(pageSize);

            ViewBag.PageCount = pageCount;
            ViewBag.PageIndex = pageIndex;
            ViewBag.ProductId = id;

            return View(await resultRecords.ToListAsync());
        }

        // GET: AnemometerRecords/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var anemometerRecord = await _context.AnemometerRecords
                .FirstOrDefaultAsync(m => m.Id == id);
            if (anemometerRecord == null)
            {
                return NotFound();
            }

            return View(anemometerRecord);
        }

        public async Task<IActionResult> DownLoads(DateTime? startTime, DateTime? stopTime, string id)
        {
            var records = from record in _context.AnemometerRecords
                where record.ProductId == id
                select record;

            if (startTime != null)
            {
                records = records.Where(s => s.RecordDate >= startTime);
            }

            if (stopTime != null)
            {
                records = records.Where(s => s.RecordDate <= stopTime);
            }

            var tempRecords = await records.ToListAsync();

            using (var memoryStream = new MemoryStream())
            {
                var streamWriter = new StreamWriter(memoryStream);

                foreach (var record in tempRecords)
                {
                    streamWriter.WriteLine($"N2S: " + record.N2S + "m/s E2W: " + record.E2W + "m/s Velcoity: " +
                                           record.Velocity +
                                           "m/s Direction: " + record.Direction + "° SoundVelocity: " +
                                           record.SoundVelocity + "m/s " + record.RecordDate);
                    streamWriter.Flush();
                }

                return File(memoryStream.GetBuffer(), "text/plain", "record.txt");
            }
        }

        // GET: AnemometerRecords/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: AnemometerRecords/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,E2W,N2S,Velocity,Direction,SoundVelocity,ProductId")] AnemometerRecord anemometerRecord)
        {
            if (ModelState.IsValid)
            {
                _context.Add(anemometerRecord);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(anemometerRecord);
        }

        // GET: AnemometerRecords/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var anemometerRecord = await _context.AnemometerRecords.FindAsync(id);
            if (anemometerRecord == null)
            {
                return NotFound();
            }
            return View(anemometerRecord);
        }

        // POST: AnemometerRecords/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,E2W,N2S,Velocity,Direction,SoundVelocity")] AnemometerRecord anemometerRecord)
        {
            if (id != anemometerRecord.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(anemometerRecord);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AnemometerRecordExists(anemometerRecord.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(anemometerRecord);
        }

        // GET: AnemometerRecords/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var anemometerRecord = await _context.AnemometerRecords
                .FirstOrDefaultAsync(m => m.Id == id);
            if (anemometerRecord == null)
            {
                return NotFound();
            }

            return View(anemometerRecord);
        }

        // POST: AnemometerRecords/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var anemometerRecord = await _context.AnemometerRecords.FindAsync(id);
            _context.AnemometerRecords.Remove(anemometerRecord);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AnemometerRecordExists(int id)
        {
            return _context.AnemometerRecords.Any(e => e.Id == id);
        }

    }
}

SenseedDataCenter/Views/AnemometerRecords/Create.cshtml
@model SenseedDataCenter.Models.AnemometerRecord

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>AnemometerRecord</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="E2W" class="control-label"></label>
                <input asp-for="E2W" class="form-control" />
                <span asp-validation-for="E2W" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="N2S" class="control-label"></label>
                <input asp-for="N2S" class="form-control" />
                <span asp-validation-for="N2S" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Velocity" class="control-label"></label>
                <input asp-for="Velocity" class="form-control" />
                <span asp-validation-for="Velocity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Direction" class="control-label"></label>
                <input asp-for="Direction" class="form-control" />
                <span asp-validation-for="Direction" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SoundVelocity" class="control-label"></label>
                <input asp-for="SoundVelocity" class="form-control" />
                <span asp-validation-for="SoundVelocity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SenseedDataCenter/Views/AnemometerRecords/Delete.cshtml
@model SenseedDataCenter.Models.AnemometerRecord

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>AnemometerRecord</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.E2W)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.E2W)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.N2S)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.N2S)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Velocity)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Velocity)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Direction)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Direction)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SoundVelocity)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SoundVelocity)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

SenseedDataCenter/Views/AnemometerRecords/Details.cshtml
@model SenseedDataCenter.Models.AnemometerRecord

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>AnemometerRecord</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.E2W)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.E2W)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.N2S)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.N2S)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Velocity)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Velocity)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Direction)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Direction)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SoundVelocity)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SoundVelocity)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

SenseedDataCenter/Views/AnemometerRecords/Edit.cshtml
@model SenseedDataCenter.Models.AnemometerRecord

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>AnemometerRecord</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="E2W" class="control-label"></label>
                <input asp-for="E2W" class="form-control" />
                <span asp-validation-for="E2W" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="N2S" class="control-label"></label>
                <input asp-for="N2S" class="form-control" />
                <span asp-validation-for="N2S" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Velocity" class="control-label"></label>
                <input asp-for="Velocity" class="form-control" />
                <span asp-validation-for="Velocity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Direction" class="control-label"></label>
                <input asp-for="Direction" class="form-control" />
                <span asp-validation-for="Direction" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SoundVelocity" class="control-label"></label>
                <input asp-for="SoundVelocity" class="form-control" />
                <span asp-validation-for="SoundVelocity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SenseedDataCenter/Views/AnemometerRecords/Index.cshtml
@model IEnumerable<SenseedDataCenter.Models.AnemometerRecord>

@{
    ViewData["Title"] = "Index";
}

@{
    var pageindex = Convert.ToInt32(ViewBag.PageIndex);
    var pagecount = Convert.ToInt32(ViewBag.PageCount);
    var productId = Convert.ToString(ViewBag.ProductId);
    var pagestart = pageindex - 2 > 0 ? pageindex - 2 : 1;
    var pageend = pageindex + 2 >= pagecount ? pagecount : pagestart + 4;
}

<h2>数据信息</h2>

<form>
    <p>
        起始时间: <input type="datetime" name="startTime">
        中止时间: <input type="datetime" name="stopTime">
        <input type="submit" value="搜索" asp-action="Index" asp-controller="AnemometerRecords"/>
        <input type="submit" value="下载" asp-action="DownLoads" asp-controller="AnemometerRecords" asp-route-id="@productId"/>
    </p>

</form>

<table class="table">
    <thead>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.E2W)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.N2S)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Velocity)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Direction)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SoundVelocity)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RecordDate)
        </th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.E2W)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.N2S)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Velocity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Direction)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SoundVelocity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RecordDate)
            </td>
        </tr>
    }
    </tbody>
</table>
<nav>
    <ul class="pagination">
        <li class="@(pageindex == 1 ? "disabled" : "")">
            <a asp-action="Index" asp-route-pageindex="@(pageindex == 1 ? 1 : pageindex - 1)">
                &laquo;
            </a>
        </li>
        @for (int i = pagestart; i <= pageend; i++)
        {
            <li @(pageindex == i ? "class = active" : "")>
                <a asp-action="Index" asp-route-pageindex="@i">
                    @i
                </a>
            </li>
        }
        <li class="@(pageindex == pagecount ? "disabled" : "")">
            <a asp-action="Index" asp-route-pageindex="@(pageindex == pagecount ? pagecount : pageindex + 1)">
                &raquo;
            </a> 
        </li>
    </ul>
</nav>